name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  IDF_VERSION: release/v4.2

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

      - uses: actions/checkout@v3

      - name: Build
        run: docker build -t station .

      - name: Copy files
        run: docker run --rm --entrypoint cat station ./build/wifi_station.bin > ./wifi_station.bin

      - name: Artifact
        run: mkdir build && cp ./wifi_station.bin build/wifi_station.bin
        
      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with: build
          name: build
          path: ./build
