name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  IDF_VERSION: origin/release/v4.2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Packages Install
        run: sudo apt-get install git wget flex bison gperf python3 python3-venv cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0
      
      - name: Python Version
        run: python --version

      - name: Clone IDF
        run: mkdir -p ~/esp && cd ~/esp && git clone -b ${{env.IDF_VERSION}} --recursive https://github.com/espressif/esp-idf.git

      - name: Setup Tools
        run: ~/esp/esp-idf/install.sh esp32

      - name: Test Build
        run: . $HOME/esp/esp-idf/export.sh && cd ~/esp/esp-idf/examples/wifi/getting_started/station && idf.py build
        
