name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  IDF_VERSION: release/v4.2

jobs:
  build:
    runs-on: ubuntu-latest
    container: bindertronics/esp32-idf:4.2-0.0.1
    
    steps:

      - uses: actions/checkout@v3

      - name: LS
        run: ls

      # - name: Pull Image
      #   run: docker pull docker build -t station . 

      # - name: Clone IDF
      #   run: mkdir -p ~/esp && cd ~/esp && git clone -b ${{env.IDF_VERSION}} --recursive https://github.com/espressif/esp-idf.git

      # - name: Setup Tools
      #   run: ~/esp/esp-idf/install.sh esp32

      # - name: Test Build
      #   run: . $HOME/esp/esp-idf/export.sh && cd ~/esp/esp-idf/examples/wifi/getting_started/station && idf.py build
        
