name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  BULD_NAME: wifi_station

jobs:
  build:
    runs-on: bindertronics/esp32-idf:4.2-0.0.2
    
    steps:

      - uses: actions/checkout@v3

      - name: cd
        run: cd ./station

      - name: Build
        run: idf.py build

      - name: Artifact
        run: |
          mkdir build
          cp ./${{env.BULD_NAME}}.bin build/${{env.BULD_NAME}}.bin
        
      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./build
