name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  BULD_NAME: wifi_station

jobs:
  build:
    runs-on: ubuntu-latest
    container: bindertronics/esp32-idf:4.2-0.0.2
    
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          cd ./station
          idf.py build

      - name: Artifact
        run: |
          mkdir build
          cp ./${{env.BULD_NAME}}.bin ./station/build/${{env.BULD_NAME}}.bin
        
      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./station/build
